### ISSUE TITLE
Err 500 

### ISSUE THREAD

**Issue by letheriver2007** [lctoolsweb/lct-transmit#1]
```
收到来自ip: ::ffff:127.0.0.1，uid:10001 执行了 /give 102 x1
请求失败： AxiosError: Parse Error: Expected HTTP/
    at AxiosError.from (G:\lct-transmit-main\node_modules\axios\dist\node\axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (G:\lct-transmit-main\node_modules\axios\dist\node\axios.cjs:3086:25)
    at RedirectableRequest.emit (node:events:514:28)
    at eventHandlers.<computed> (G:\lct-transmit-main\node_modules\follow-redirects\index.js:38:24)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketOnData (node:_http_client:550:9)
    at Socket.emit (node:events:514:28)
    ... 2 lines matching cause stack trace ...
    at Readable.push (node:internal/streams/readable:234:10)
    at Axios.request (G:\lct-transmit-main\node_modules\axios\dist\node\axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  rawPacket: <Buffer 15 03 03 00 02 02 50>,
  reason: 'Expected HTTP/',
  code: 'HPE_INVALID_CONSTANT',
  bytesParsed: 0,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.6.8',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    params: { uid: '10001', command: '/give 102 x1', password: '123456' },
    method: 'get',
    url: 'http://127.0.0.1:443/api/gm',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/api/gm?uid=10001&command=%2Fgive+102+x1&password=123456',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '127.0.0.1',
      port: '443',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/gm',
      search: '?uid=10001&command=%2Fgive+102+x1&password=123456'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/gm?uid=10001&command=%2Fgive+102+x1&password=123456 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.6.8\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 127.0.0.1:443\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/gm?uid=10001&command=%2Fgive+102+x1&password=123456',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://127.0.0.1:443/api/gm?uid=10001&command=%2Fgive+102+x1&password=123456',
    [Symbol(kCapture)]: false
  },
  cause: Error: Parse Error: Expected HTTP/
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    bytesParsed: 0,
    code: 'HPE_INVALID_CONSTANT',
    reason: 'Expected HTTP/',
    rawPacket: <Buffer 15 03 03 00 02 02 50>
  }
}
POST /submit 500 5.737 ms - 24
```
![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/df8c3471-c15c-4a0c-b04e-12690b9560e9)

```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 24
ETag: W/"18-/5FW1Tgl1UeaYttof+Okvrs+XjM"
Date: Thu, 11 Apr 2024 15:06:43 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"error":"请求失败"}
```
大佬求教 QwQ

**Comment by letheriver2007** [comment]
![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/377f0c5f-1b01-4385-aff8-0d73b616351e)

**Comment by moraxs** [comment]
```
method: 'get',
    url: 'http://127.0.0.1:443/api/gm',
    data: undefined
```
The error appears here and the /api/gm route is not found，the official core does not have this route, please use the dedicated core in the README.

**Comment by letheriver2007** [comment]
好的 谢谢大佬
(我把lc路径找错了，看成lctoolsweb下的那个了。。。

**Comment by letheriver2007** [comment]
大佬，仍然报500的错误
![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/1a0ead8c-f6dc-4fcf-873e-8e33747b34cd)
我已经满足如下使用需求
 - 使用lctoolweb
 - 使用lct-transmit
 - 使用魔改lc

我注意到jsonrequest为空，请问是否和这有关？
![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/74e3d48c-cd64-441e-99ac-3a359dac0fdc)

**Comment by moraxs** [comment]
![FK%ORX`)($2 FE}NVI0XW$0](https://github.com/lctoolsweb/lct-transmit/assets/98573765/6af31798-ef08-4f6d-a56b-e3627c039095)
应该好了，忘记点保存直接提交了(bushi

**Comment by letheriver2007** [comment]
![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/a37e9397-ae8d-47ee-a083-d019277dcdb7)

![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/4bc9d9f1-95e2-4a6b-8edc-0c9e23f5dcbc)

也不知道啥情况了（悲

![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/e4e3afd9-b088-4238-a4c7-f7c427918c35)

报错和原来一样undefined
看起来还是lc的问题 我这里新写了一个转发，报错一模一样（不过我这个转发用lctoolweb访问报CORS,用GUI可以
本地重新编译也一样

**Comment by moraxs** [comment]
是不是用的最新action

**Comment by letheriver2007** [comment]
是最新的那个fix bugs #9

**Comment by moraxs** [comment]
[img1](https://img.morax.top/file/86f52c878bf533d1a008d.jpg)
[img2](https://img.morax.top/file/bea48648e35076b54ab9f.jpg)
经测试，在lc，转发端和lct都是最新版本的情况下，远程正常工作。
确保tools.js中的url为正确的lc地址，默认为127.0.0.1:443/api/gm ，lct中的远程地址为tools.js实际运行的地址，默认为127.0.0.1:2237/submit。确保防火墙已经开放相关的端口

**Comment by letheriver2007** [comment]
![image](https://github.com/lctoolsweb/lct-transmit/assets/77842352/de417d5b-0a1c-46a0-ad46-1cf86be76f2d)
方便问一下大佬这里的写法吗，似乎找到问题了
我浏览器访问dispatch进不去，显示无效的响应

**Comment by letheriver2007** [comment]
谢谢佬帮忙，原因已找到，由于我没有正确配置LC的config.json，转发服务器无法访问443导致。
以下是修改后的配置：
# config.json
```
  "httpServer": {
    "useSSL": false,
    "regionListRefresh": 60000,
    "gm_private": "melon",
    "gm_public": "melon",
    "bindAddress": "0.0.0.0",
    "bindPort": 443,
    "publicAddress": "127.0.0.1",
    "publicPort": 443
  },
  ```
  # Fiddler
  ```
import System;
import System.Windows.Forms;
import Fiddler;
import System.Text.RegularExpressions;

class Handlers
{
    static function OnBeforeRequest(oS: Session) {
        if (oS.host.EndsWith(".starrails.com") || oS.host.EndsWith(".hoyoverse.com") || oS.host.EndsWith(".mihoyo.com") || oS.host.EndsWith(".bhsr.com")) {
            oS.host = "127.0.0.1:443";
            oS.fullUrl = oS.fullUrl.Replace("https://", "http://");
        }
    }
};
```
